before_script:
  - docker info
  - echo ${date}

build_image:
  only:
    - bikram-stack
  script:
    - echo "Build pustakalaya"     
    - docker-compose -f development.yml down
    - docker-compose -f development.yml build
    - docker-compose -f development.yml up -d
    
