# Stages are run in sequence, jobs in the same stage are run in parallel
# See https://docs.gitlab.com/ce/ci/yaml/
# TODO: Correct the tags to fit your gitlab


stages:
  - prepare-images
  - push-images
  - pull-images-test
  - deploy-test
  - pull-images-live
  - deploy-live

before_script:
  - cp -rv versions /library/media_root/release_version.txt

prepare:image:
  stage: prepare-images
  script:
    - docker-compose -f build.yml build
  only:
    - tags
  tags:
    - development

# Push
# ----
# Pushes the Docker image to th registry for selected tags
push:image:
  stage: push-images
  script:
    - docker-compose -f build.yml push
  # when: manual
  only:
    - tags
  tags:
    - development

pull:production-test:pull-image:
  stage: pull-images-test
  script:
    - docker-compose -f build.yml pull
  # when: manual
  only:
    - tags
  tags:
    - production-test



deploy:production-test:
  stage: deploy-test
  script:
     - docker-compose -f production.yml down
     - docker-compose -f production.yml up -d
#    - docker stack deploy --compose-file django-swarm.yml pusta
  only:
    - tags
  tags:
    - production-test

pull:production-live:pull-image:
  stage: pull-images-live
  script:
    - docker-compose -f build.yml pull
  when: manual
  only:
    - tags
  tags:
    - production

deploy:production-live:pull-image:
  stage: deploy-live
  script:
    - docker-compose -f production.yml down
    - docker-compose -f production.yml up -d
  only:
    - tags
  when: manual
  tags:
    - production
