before_script:
  - docker info
  - echo ${date}
  

build_image:
  only:
    - bikram-stack
  script:
    - echo "Build pustakalaya"
    - docker-compose -f development.yml down
    - sleep 10 && docker volume prune -f
    - docker-compose -f development.yml up  --build  -d
