# Stages are run in sequence, jobs in the same stage are run in parallel
# See https://docs.gitlab.com/ce/ci/yaml/
# TODO: Correct the tags to fit your gitlab


stages:
  - prepare
  - build
  - deploy

# Specify custom variables
# variables:
#   # Enables multibranch build
#   COMPOSE_PROJECT_NAME: $CI_PROJECT_NAME-$CI_BUILD_REF_NAME
#   # How to store the image
#   IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
before_script:
  - ./get_release_version.sh
# Prepare
# -------
# Removes old images and containers, if they exist
################################################
prepare:clean:
  stage: prepare
  script:
    # Stop all containers
    - docker-compose -f development.yml down
    - docker-compose -f production.yml down
    # Remove all containers and volumes
    - docker-compose -f development.yml rm -fv
    - docker-compose -f production.yml rm -fv
  tags:
    - development
##################################################
# Install
# -------
# Build all images
build:containers:
  stage: build
  script:
    # Build the Containers without caching and newest source image
    - docker-compose -f build.yml  build --pull
  tags:
    - development

# Push
# ----
# Pushes the Docker image to th registry for selected tags
deploy:production:
  stage: deploy
  script:
    # Login to the registry
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    # Push images to the gitlab remote
    - echo "${RELEASE_TAG} on $(date)" >> /library/media_root/release_version.txt
    # - docker-compose -f production.yml push
    - docker-compose -f production.yml up -d

  # Only these branches are getting pushed
  # when: manual
  only:
    - bikram-stack
  tags:
    - development
# Deploy
# ------
# Starts the containers
deploy:development:
  stage: deploy
  script:
    # Bring up the app
    - docker-compose -f development.yml up -d
  only:
    - bikram-stack
  tags:
    - development
