before_script:
  - docker info
  - echo ${date}



build_run_pustakalaya:
  stage: deploy
  only:
    - bikram-stack
  script:
    - "curl -X POST -F token=b7cebd5946e7c83a3048950a733e0b -F ref=bikram-stack http://git.olenepal.org/api/v4/projects/74/trigger/pipeline"
    - echo "Build pustakalaya"
    - docker-compose -f development.yml down
    - docker-compose -f development.yml up  --build  -d
