stages:
  - destory
  - build
  - run

before_script:
  - docker info




destroy_docker:
  stage: destroy
  only:
    - bikram-stack
  script:
    - "curl -X POST -F token=b7cebd5946e7c83a3048950a733e0b -F ref=bikram-stack http://git.olenepal.org/api/v4/projects/74/trigger/pipeline"
    - docker-compose -f development.yml down


build_docker:
  stage: build
  only:
    - bikram-stack
  script:
    - "curl -X POST -F token=b7cebd5946e7c83a3048950a733e0b -F ref=bikram-stack http://git.olenepal.org/api/v4/projects/74/trigger/pipeline"
    - docker-compose -f development.yml build

run_docker:
  stage: run
  only:
    - bikram-stack
  script:
    - "curl -X POST -F token=b7cebd5946e7c83a3048950a733e0b -F ref=bikram-stack http://git.olenepal.org/api/v4/projects/74/trigger/pipeline"
    - docker-compose -f development.yml up -d
