version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:v25.35.0
    build:
      context: ./dockerfile-nginx/
      dockerfile: Dockerfile.build

  code:
    build:
      context: .
      dockerfile: ./dockerfile-code/Dockerfile.build
    image: becram/olen-elib-code:v25.35.0

  pgmaster:
    image: becram/olen-elib-db-master:v25.35.0
    build:
      context: ./dockerfile-postgres-master
      dockerfile: Dockerfile.build

  pgslave:
    image: becram/olen-elib-db-slave:v25.35.0
    build:
      context: ./dockerfile-postgres-slave
      dockerfile: Dockerfile.build


  elastic:
    image: becram/olen-elib-elastic:v25.35.0
    build:
      context: ./dockerfile-elastic
      dockerfile: Dockerfile.build


  rabbitmq:
    image: rabbitmq:3.7


  celery:
    image: becram/olen-elib-celery:v25.35.0
    build:
      context: .
      dockerfile: ./dockerfile-celery/Dockerfile.build


  # kibana:
  #   image: becram/olen-elib-kibana:s1.0
  #   build:
  #     context: ./dockerfile-kibana
  #     dockerfile: Dockerfile.build
  #   container_name: pusta_kibana_01
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elastic:9200
  #   networks:
  #     - elk
  #
  # logstash:
  #   image: becram/olen-elib-logstash:s1.0
  #   build:
  #     context: ./dockerfile-logstash
  #     dockerfile: Dockerfile.build
  #   hostname: logstash
  #   container_name: pusta_logstash_01
  # #  command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elastic:9200\" ] } }'"
  #   ports:
  #     - "8050:5000"
  #     - "8012:12201/udp"
  #   networks:
  #     - elk


# volumes:
#   postgres_data_slave:
#   postgres_data_master:
#   postgres_dump:
#   pusta_elastic:
#
#
#
# networks:
#   elk:
#     driver: bridge
