version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:s1.0
    build:
      context: ./dockerfile-nginx/
      dockerfile: Dockerfile.dev
    restart: always
    hostname: nginx
    container_name: pusta_nginx_01
    networks:
      - elk

    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:8012
        tag: nginx
    ports:
     - "81:8000"
    volumes:
            - /library/media_root:/library/media_root:rw
            - /library/static_root:/library/static_root:rw
    depends_on:
     - web
  web:
    build:
      context: .
      dockerfile: ./dockerfile-django-web/Dockerfile.dev
    image: becram/olen-elib-code:s1.0
    restart: always
    hostname: web
    container_name: pusta_web_01
    environment:
      - GUNICORN_NAME=pustakalaya
      - GUNICORN_NUM_WORKERS=4
      - DJANGO_WSGI_MODULE=pustakalaya.wsgi
    depends_on:
      - pgmaster
      - elastic
      - pgslave
      - celery
      - rabbitmq

    volumes:
            - /library/media_root:/library/media_root:rw
            - /library/static_root:/library/static_root:rw
    networks:
      - elk
#    ports:
#      - "8001:8001"
    expose:
      - "8001"


  pgmaster:
    image: becram/olen-elib-db:s1.0
    build:
      context: ./dockerfile-postgres
      dockerfile: postgres-9.6-repmagr.Dockerfile
    restart: 'always'
    hostname: pgmaster
    container_name: pusta_pgmaster_01
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - POSTGRES_BACKUP_DIR=/pg_backups
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - postgres_data_master:/var/lib/postgresql/data
     - postgres_dump:/pg_backups
    expose:
     - '5432'
    networks:
      - elk

  pgslave:
    image: becram/olen-elib-db:s1.0
    build:
      context: ./dockerfile-postgres
      dockerfile: postgres-9.6-repmagr.Dockerfile
    restart: 'always'
    hostname: db-slave
    container_name: pusta_pgslave_01
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - POSTGRES_BACKUP_DIR=/pg_backups
      - PGDATA=/var/lib/postgresql/data/pgdata
      - REPLICATE_FROM=pgmaster
    volumes:
      - postgres_data_slave:/var/lib/postgresql/data
    expose:
      - '5432'
    depends_on:
      - pgmaster
    networks:
      - elk


  elastic:
    image: becram/olen-elib-elastic:s1.0
    build:
      context: ./dockerfile-elastic
      dockerfile: Dockerfile.dev
    hostname: elastic
    restart: always
    container_name: pusta_elasticsearch_01
    volumes:
      - ./conf:/conf
    networks:
      - elk
    # command: ./run_db.sh
    depends_on:
      - pgmaster
    expose:
      -  "9200"
      -  "9300"
    ports:
      -  '9200:9200'


  rabbitmq:
    image: rabbitmq:3.7
    hostname: rabbitmq
    restart: always
    container_name: pusta_rabbitmq_01
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - elk

  celery:
    image: becram/olen-elib-celery:s1.0
    build:
      context: .
      dockerfile: ./dockerfile-celery/Dockerfile.dev
    hostname: celery
    restart: always
    container_name: pusta_celery_01
    networks:
      - elk
    depends_on:
      - pgmaster
      - rabbitmq

        #  kibana:
        #    image: becram/olen-elib-kibana:s1.0
        #    build:
        #      context: ./dockerfile-kibana
        #      dockerfile: Dockerfile.dev
        #    container_name: pusta_kibana_01
        #    ports:
        #      - "5601:5601"
        #    environment:
        #      ELASTICSEARCH_URL: http://elastic:9200
        #    networks:
        #      - elk
        #
        #    
        #  logstash:
        #    image: becram/olen-elib-logstash:s1.0
        #    build:
        #      context: ./dockerfile-logstash
        #      dockerfile: Dockerfile.dev
        #    hostname: logstash
        #    container_name: pusta_logstash_01
        #    command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elastic\" ] } }'"
        #    ports:
        #      - "10514:10514/tcp"
        #      - "10514:10514/udp"
        #      - "12201:12201/udp"
        #    networks:
        #      - elk
        #

volumes:
  postgres_data_slave:
  postgres_data_master:
  postgres_dump:



networks:
  elk:
    driver: bridge
