version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:s1.1
    build:
      context: ./dockerfile-nginx/
      dockerfile: Dockerfile.dev


  web:
    build:
      context: .
      dockerfile: ./dockerfile-code/Dockerfile.dev
    image: becram/olen-elib-code:s1.1

  pgmaster:
    image: becram/olen-elib-db-master:s1.1
    build:
      context: ./dockerfile-postgres-master
      dockerfile: Dockerfile.dev

  pgslave:
    image: becram/olen-elib-db-slave:s1.1
    build:
      context: ./dockerfile-postgres-slave
      dockerfile: Dockerfile.dev


  elastic:
    image: becram/olen-elib-elastic:s1.1
    build:
      context: ./dockerfile-elastic
      dockerfile: Dockerfile.dev


  rabbitmq:
    image: rabbitmq:3.7


  celery:
    image: becram/olen-elib-celery:s1.1
    build:
      context: .
      dockerfile: ./dockerfile-celery/Dockerfile.dev


  # kibana:
  #   image: becram/olen-elib-kibana:s1.0
  #   build:
  #     context: ./dockerfile-kibana
  #     dockerfile: Dockerfile.dev
  #   container_name: pusta_kibana_01
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elastic:9200
  #   networks:
  #     - elk
  #
  # logstash:
  #   image: becram/olen-elib-logstash:s1.0
  #   build:
  #     context: ./dockerfile-logstash
  #     dockerfile: Dockerfile.dev
  #   hostname: logstash
  #   container_name: pusta_logstash_01
  # #  command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elastic:9200\" ] } }'"
  #   ports:
  #     - "8050:5000"
  #     - "8012:12201/udp"
  #   networks:
  #     - elk


# volumes:
#   postgres_data_slave:
#   postgres_data_master:
#   postgres_dump:
#   pusta_elastic:
#
#
#
# networks:
#   elk:
#     driver: bridge
