version: '2'
services:
  nginx:
    # image: nginx:latest
#    image: funkygibbon/nginx-pagespeed:latest
    build:
      context: ./dockerfile-nginx/
      dockerfile: Dockerfile
    restart: always
    hostname: nginx
    container_name: nginx_01
    networks:
      - pustakalaya-network
    ports:
     - "80:8000"
    volumes:
     - ./src:/src
#     - ./conf/nginx:/etc/nginx/conf.d
     - /library/media_root:/library/media_root
     - /library/static_root:/library/static_root
    depends_on:
     - web
  web:
    build:
      context: .
      dockerfile: ./dockerfile-django-web/Dockerfile
    restart: always
    hostname: web
    container_name: django_web_01
    command: ./script.d/run_web
    depends_on:
      - db
      - elastic
    volumes:
      - ./src:/src
      - /library/media_root:/library/media_root
      - /library/static_root:/library/static_root
    networks:
      - pustakalaya-network
#    ports:
#      - "8001:8001"
    expose:
      - "8001"
#    links:
#      - redis
  db:
    build:
      context: ./dockerfile-postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - POSTGRES_BACKUP_DIR=/pg_backups
      # - BUILD_NUM=${BUILD_NUMBER}

    hostname: db
    container_name: postgres_01
    networks:
      - pustakalaya-network
     # command: ./run_db.sh
    volumes:
      - /library/backup_pg_pustakalaya:/pg_backups
      - ./src:/src
    expose:
      - "5432"


  elastic:
    build:
      context: ./dockerfile-elastic
      dockerfile: Dockerfile
    hostname: elastic
    restart: always
    container_name: elasticsearch_01
    volumes:
      - ./conf:/conf
    networks:
      - pustakalaya-network
    # command: ./run_db.sh
    depends_on:
      - db
    expose:
      -  "9200"
      -  "9300"
    #ports:
    #  -  '9200:9200'

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq_01
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    expose:
      - "5672"
    networks:
      - pustakalaya-network

  celery:
    build:
      context: .
      dockerfile: ./dockerfile-celery/Dockerfile
    hostname: celery
    restart: always
    container_name: celery_01
    command: celery -A pustakalaya  worker -l info
    networks:
      - pustakalaya-network
    volumes:
      - ./src:/src
      - /library/media_root:/library/media_root
      - /library/static_root:/library/static_root

    links:
      - db
      - rabbitmq
   


networks:
  pustakalaya-network:
    driver: bridge
