version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:stable-s1.4
    restart: always
    networks:
      - net-pusta
    ports:
      - "80:8000"
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    depends_on:
     - code


  code:
    image: becram/olen-elib-code:stable-s1.4
    restart: always
    env_file:
      - ./dockerfile-code/code.env
    depends_on:
      - pgmaster
      - elastic
      - pgslave
      - celery
      - rabbitmq

    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    networks:
      - net-pusta



  pgmaster:
    image: becram/olen-elib-db-master:stable-s1.4
    restart: 'always'
    env_file:
      - ./dockerfile-postgres-master/pgmaster.env
    volumes:
     - production_postgres_data_master:/var/lib/postgresql/data
     - /library/backup/postgres_backup:/backup/postgres_backup
    networks:
      - net-pusta

  pgslave:
    image: becram/olen-elib-db-slave:stable-s1.4
    restart: 'always'
    hostname: db-slave
    env_file:
      - ./dockerfile-postgres-slave/pgslave.env
    volumes:
      - production_postgres_data_slave:/var/lib/postgresql/data
    depends_on:
      - pgmaster
    networks:
      - net-pusta


  elastic:
    image: becram/olen-elib-elastic:stable-s1.4
    hostname: elastic
    environment:
      # server memory dependent
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: always
    volumes:
      - ./conf:/conf
    volumes:
      - production_elastic_data:/usr/share/elasticsearch/data
    networks:
      - net-pusta
    depends_on:
      - pgmaster

  rabbitmq:
    image: rabbitmq:3.7
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - net-pusta

  celery:
    image: becram/olen-elib-celery:stable-s1.4
    hostname: celery
    restart: always
    networks:
      - net-pusta
    depends_on:
      - pgmaster
      - rabbitmq


volumes:
  production_postgres_data_slave:
  production_postgres_data_master:
  production_elastic_data:



networks:
  net-pusta:
    driver: bridge
