version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:${RELEASE_TAG}
    restart: always
    container_name: prod_nginx_${RELEASE_TAG}
    networks:
      - net-pusta
    ports:
      - "80:8000"
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    depends_on:
     - web


  code:
    image: becram/olen-elib-code:${RELEASE_TAG}
    restart: always
    container_name: pusta_code_${RELEASE_TAG}
    env_file:
      - ./dockerfile-code/code.env
    depends_on:
      - pgmaster
      - elastic
      - pgslave
      - celery
      - rabbitmq

    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    networks:
      - net-pusta



  pgmaster:
    image: becram/olen-elib-db-master:${RELEASE_TAG}
    restart: 'always'
    container_name: pusta_pgmaster_${RELEASE_TAG}
    env_file:
      - ./dockerfile-postgres-master/pgmaster.env
    volumes:
     - postgres_data_master:/var/lib/postgresql/data
     - postgres_dump:/pg_backups
    networks:
      - net-pusta

  pgslave:
    image: becram/olen-elib-db-slave:${RELEASE_TAG}
    restart: 'always'
    hostname: db-slave
    container_name: pusta_pgslave_${RELEASE_TAG}
    env_file:
      - ./dockerfile-postgres-slave/pgslave.env
    volumes:
      - postgres_data_slave:/var/lib/postgresql/data
    depends_on:
      - pgmaster
    networks:
      - net-pusta


  elastic:
    image: becram/olen-elib-elastic:${RELEASE_TAG}
    hostname: elastic
    environment:
      # server memory dependent
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: always
    container_name: pusta_elasticsearch_${RELEASE_TAG}
    volumes:
      - ./conf:/conf
    volumes:
      - pusta_elastic:/usr/share/elasticsearch/data
    networks:
      - net-pusta
    depends_on:
      - pgmaster

  rabbitmq:
    image: rabbitmq:3.7
    hostname: rabbitmq
    restart: always
    container_name: pusta_rabbitmq_01
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - net-pusta

  celery:
    image: becram/olen-elib-celery:${RELEASE_TAG}
    hostname: celery
    restart: always
    container_name: pusta_celery_${RELEASE_TAG}
    networks:
      - net-pusta
    depends_on:
      - pgmaster
      - rabbitmq


volumes:
  postgres_data_slave:
  postgres_data_master:
  postgres_dump:
  pusta_elastic:



networks:
  net-pusta:
    driver: bridge
