version: '2'
services:
  nginx:
    image: becram/olen-elib-nginx:{{RELEASE}}
    restart: always
    container_name: prod_nginx_{{RELEASE}}
    networks:
      - net-pusta
    ports:
      - "80:8000"
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    depends_on:
     - web


  code:
    image: becram/olen-elib-code:{{RELEASE}}
    restart: always
    container_name: pusta_code_{{RELEASE}}
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DJANGO_DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DJANGO_DATABASE_HOST=pgmaster
      - DJANGO_DATABASE_NAME=pustakalaya
      - DJANGO_DATABASE_USER=pustakalaya_user
      - DJANGO_DATABASE_PASSWORD=pustakalaya123
      - DJANGO_LOGSTASH_HOST=logstash
      - DJANGO_LOGSTASH_PORT=5000
      - GUNICORN_NAME=pustakalaya
      - GUNICORN_NUM_WORKERS=4
      - DJANGO_WSGI_MODULE=pustakalaya.wsgi
    depends_on:
      - pgmaster
      - elastic
      - pgslave
      - celery
      - rabbitmq

    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    networks:
      - net-pusta



  pgmaster:
    image: becram/olen-elib-db-master:{{RELEASE}}
    restart: 'always'
    container_name: pusta_pgmaster_{{RELEASE}}
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - postgres_data_master:/var/lib/postgresql/data
     - postgres_dump:/pg_backups
    networks:
      - net-pusta

  pgslave:
    image: becram/olen-elib-db-slave:{{RELEASE}}
    restart: 'always'
    hostname: db-slave
    container_name: pusta_pgslave_{{RELEASE}}
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - REPLICATE_FROM=pgmaster
    volumes:
      - postgres_data_slave:/var/lib/postgresql/data
    depends_on:
      - pgmaster
    networks:
      - net-pusta


  elastic:
    image: becram/olen-elib-elastic:{{RELEASE}}
    hostname: elastic
    environment:
      # server memory dependent
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: always
    container_name: pusta_elasticsearch_{{RELEASE}}
    volumes:
      - ./conf:/conf
    volumes:
      - pusta_elastic:/usr/share/elasticsearch/data
    networks:
      - net-pusta
    depends_on:
      - pgmaster

  rabbitmq:
    image: rabbitmq:3.7
    hostname: rabbitmq
    restart: always
    container_name: pusta_rabbitmq_01
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - net-pusta

  celery:
    image: becram/olen-elib-celery:{{RELEASE}}
    hostname: celery
    restart: always
    container_name: pusta_celery_{{RELEASE}}
    networks:
      - net-pusta
    depends_on:
      - pgmaster
      - rabbitmq


volumes:
  postgres_data_slave:
  postgres_data_master:
  postgres_dump:
  pusta_elastic:



networks:
  net-pusta:
    driver: bridge
