version: '3'
services:
  nginx:
    image: becram/olen-elib-nginx:s1.3
    networks:
      - pustakalaya-stack-network
    ports:
     - "80:8000"
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    depends_on:
     - web

  web:
    image: becram/olen-elib-code:s1.3
    depends_on:
      - pgmaster
      - elastic
      - pgslave
      - celery
      - rabbitmq
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DJANGO_DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DJANGO_DATABASE_HOST=pgmaster
      - DJANGO_DATABASE_NAME=pustakalaya
      - DJANGO_DATABASE_USER=pustakalaya_user
      - DJANGO_DATABASE_PASSWORD=pustakalaya123
      - DJANGO_LOGSTASH_HOST=logstash
      - DJANGO_LOGSTASH_PORT=5000
      - GUNICORN_NAME=pustakalaya
      - GUNICORN_NUM_WORKERS=4
      - DJANGO_WSGI_MODULE=pustakalaya.wsgi

    networks:
      - pustakalaya-stack-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  pgmaster:
    image: becram/olen-elib-db-master:s1.3
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - stack_pgdata_master:/var/lib/postgresql/data
      - stack_dump:/pg_backups
    networks:
      - pustakalaya-stack-network
    deploy:
      placement:
        constraints: [node.role == manager]

  pgslave:
    image: becram/olen-elib-db-slave:s1.3
    environment:
      - POSTGRES_USER=pustakalaya_user
      - POSTGRES_DB=pustakalaya
      - POSTGRES_PASSWORD=pustakalaya123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - REPLICATE_FROM=pgmaster
    volumes:
      - stack_pgdata_slave:/var/lib/postgresql/data
    networks:
      - pustakalaya-stack-network
    depends_on:
      - pgmaster
    deploy:
      placement:
        constraints: [node.role == manager]

  elastic:
    image: becram/olen-elib-elastic:s1.3
    networks:
      - pustakalaya-stack-network
    volumes:
      - stack_elastic:/usr/share/elasticsearch/data
    depends_on:
      - pgmaster

  rabbitmq:
    image: rabbitmq:3.7
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - pustakalaya-stack-network

  celery:
    image: becram/olen-elib-celery:s1.3
    networks:
      - pustakalaya-stack-network
    depends_on:
      - pgmaster
      - rabbitmiq
    volumes:
      - /library/media_root:/library/media_root:rw
      - /library/static_root:/library/static_root:rw


#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - pustakalaya-stack-network

volumes:
  stack_pgdata_slave:
  stack_pgdata_master:
  stack_dump:
  stack_elastic:



networks:
  pustakalaya-stack-network:
    driver: overlay
