# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0029_auto_20180510_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file_type',
            field=models.CharField(choices=[('ppt', 'PPT'), ('doc', 'Doc'), ('docx', 'Docx'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('epub', 'Epub'), ('rtf', 'Rtf'), ('mobi', 'Mobi')], default='pdf', max_length=23, verbose_name='Document file format'),
        ),
        migrations.AlterField(
            model_name='document',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.Language', verbose_name='Language(s)'),
        ),
    ]
