# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0025_videofileupload_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='submitted_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
