# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_videoembedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoembedlink',
            name='video_audio_link_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Embed Link Description'),
        ),
        migrations.AlterField(
            model_name='videoembedlink',
            name='video_audio_link_name',
            field=models.URLField(max_length=500, verbose_name='Embed Link URL'),
        ),
    ]
