FROM python:3.6.5

ENV PYTHONUNBUFFERED 1
RUN apt-get -qq update -y  && apt-get -qq upgrade -y  && apt-get -qq install -y \
    python-dev python-setuptools python-pip
RUN apt-get autoremove -y

# upgrade pip
RUN pip install --upgrade pip


RUN mkdir -p /library/media_root
RUN mkdir -p  /library/static_root
#RUN chmod -R 760 /library/media_root
#RUN chmod -R 760 /library/static_root

RUN mkdir /config
ADD src/requirements/requirements_dev.txt /config/
ADD src/requirements/base.txt /config/
ADD src/requirements/requirements_dev.txt /config/
RUN pip  --quiet  install -r /config/requirements_dev.txt

# Prepare user
ENV APP_USER myapp
RUN adduser --disabled-password --gecos '' ${APP_USER}


ENV APP_ROOT /src
RUN mkdir /src



RUN chown -R ${APP_USER}:${APP_USER} /library/media_root
RUN chown -R ${APP_USER}:${APP_USER} /library/static_root
RUN chown -R ${APP_USER}:${APP_USER} /src
RUN chown -R ${APP_USER}:${APP_USER} /var/log


WORKDIR ${APP_ROOT}


#Set timezone
ENV TZ=Asia/Kathmandu
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Prepare ports
# django
EXPOSE 8001

USER ${APP_USER}

# Prepare initial

#COPY ./dockerfile-code/entrypoint.sh /src/entrypoint.sh



ENTRYPOINT ["/src/entrypoint.sh"]
