# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0025_auto_20180510_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='submitted_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
