# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustakalaya_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone no'),
        ),
    ]
