FROM postgres:9.6

RUN apt-get update && apt-get -y install cron

ENV APP_ROOT /src
ENV BACKUP_DIR /library/backup_pg_pustakalaya/backup/daily/pustakalaya/

WORKDIR ${APP_ROOT}

RUN mkdir -p $BACKUP_DIR
ADD autopgsqlbackup /script/
ADD *.bz2 $BACKUP_DIR
RUN chmod +x /script/autopgsqlbackup

# Add crontab file in the cron directory
ADD crontab /etc/cron.d/simple-cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/simple-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log


#Set timezone
ENV TZ=Asia/Kathmandu
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Run the command on container startup
#CMD cron && tail -f /var/log/cron.log
# start crond with log level 8 in foreground, output to stderr
#CMD ["crond", "-f", "-d", "8"]
