FROM postgres:9.6

ENV APP_ROOT /src
ENV BACKUP_DIR /library/backup_pg_pustakalaya/backup/daily/pustakalaya/

WORKDIR ${APP_ROOT}

RUN mkdir -p $BACKUP_DIR
ADD autopgsqlbackup /script/
ADD *.bz2 $BACKUP_DIR
RUN chmod +x /script/autopgsqlbackup

#Set timezone
ENV TZ=Asia/Kathmandu
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
